### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by tarlepp**
Added JetBrains IDE specified stuff to ignore.

### CODE REVIEW

**Comment by jubianchi** [comment]
I don't really like adding this kind of things to projects' `.gitignore`. At some point, we'll have entries for IDEA, Vim, Emacs, ...

Each user should add the required ignored entries to their own `.gitignore` using something like:

```
core.excludesfile=~/.gitignore
```

Thoughts @atoum/contributors ?

**Comment by jubianchi** [comment]
@tarlepp Thanks for your contributions but we won't merge this one as explained by me and @agallou [here](https://github.com/atoum/json-schema-extension/pull/9#issuecomment-250913904)

**Comment by tarlepp** [comment]
By that you require that users make those settings - imho repository itself should take care of this.

**Comment by tarlepp** [comment]
Or at least this should be mentioned on README.md contributing guide section.

**Pull request closed without merging**
